'use client';
import {useState} from 'react';
import Link from 'next/link';
import {Users,ArrowUpRight,Check} from 'lucide-react';
import {rooms,activities,resort,type Room} from '@/data/resort';
import {money} from '@/lib/hotels';
import {tripQuery,type Trip} from '@/lib/availability';
export {RoomBooking} from './room-availability';
export function RoomCard({room:r,trip}:{room:Room;trip?:Trip}){return <article className="hotel-card"><div className="card-photo"><Link href={`/rooms/${r.slug}${trip?"?"+tripQuery(trip):""}`}><img src={`https://images.unsplash.com/${r.image}?auto=format&fit=crop&w=900&q=80`} alt={`Illustrative ${r.name} interior`} loading="lazy"/></Link><span className="photo-tag">{r.view}</span></div><div className="card-body"><h3>{r.name}</h3><p className="location"><Users size={14}/> Up to {r.guests} guests · {r.size} m²</p><p className="card-desc">{r.description}</p><div className="amenity-row"><span>{r.bed}</span><span>{r.type}</span></div><div className="card-bottom"><div><small>Sample rate / night</small><strong>{money(r.price)}</strong></div><Link className="detail-link" href={`/rooms/${r.slug}${trip?"?"+tripQuery(trip):""}`}>Explore room ↗</Link></div></div></article>;}
export function RoomBrowser({initialGuests=1,checkin="",checkout=""}:{initialGuests?:number;checkin?:string;checkout?:string}){const [guests,setGuests]=useState(initialGuests),[type,setType]=useState(''),[sort,setSort]=useState('recommended');const found=rooms.filter(r=>r.guests>=guests&&(!type||r.type===type)).sort((a,b)=>sort==='low'?a.price-b.price:sort==='high'?b.price-a.price:0);return <><div className="room-filters" id="room-selection"><label>Guests<select value={guests} onChange={e=>setGuests(+e.target.value)}>{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} guest{n>1?'s':''}</option>)}</select></label><label>Room style<select value={type} onChange={e=>setType(e.target.value)}><option value="">All rooms</option>{['Room','Suite','Cabana','Loft'].map(t=><option key={t}>{t}</option>)}</select></label><label>Sort by<select value={sort} onChange={e=>setSort(e.target.value)}><option value="recommended">Recommended</option><option value="low">Lowest price</option><option value="high">Highest price</option></select></label></div><p className="sample-note" aria-live="polite">{found.length} room types · Sample rates; check availability on the room page</p>{found.length?<div className="hotel-grid resort-rooms">{found.map(r=><RoomCard key={r.id} room={r} trip={{checkin,checkout,guests}}/>)}</div>:<div className="empty"><h3>No rooms match this combination.</h3><button className="button" onClick={()=>{setType('');setGuests(1);}}>Reset filters</button></div>}</>;}
export function ResortSearch(){const [date,setDate]=useState('');return <form className="search-bar resort-search" action="/rooms"><label><span>Check-in</span><input name="checkin" type="date" min={new Date().toISOString().slice(0,10)} value={date} onChange={e=>setDate(e.target.value)}/></label><label><span>Check-out</span><input name="checkout" type="date" min={date?new Date(new Date(date).getTime()+86400000).toISOString().slice(0,10):undefined}/></label><label><span>Guests</span><select name="guests" defaultValue="2">{[1,2,3,4,5,6].map(n=><option key={n} value={n}>{n} guests</option>)}</select></label><button className="button">Find your room <ArrowUpRight size={17}/></button></form>;}
export function ActivityBrowser({preview=false}:{preview?:boolean}){const [category,setCategory]=useState(''),[selected,setSelected]=useState('');const items=activities.filter(a=>!category||a.category===category).slice(0,preview?3:99);return <>{!preview&&<div className="trip-row">{['','Adventure','At the resort','Wellness','Dining'].map(c=><button className={category===c?'selected':''} aria-pressed={category===c} key={c} onClick={()=>setCategory(c)}>{c||'All experiences'}</button>)}</div>}<div className="explore-grid activity-grid">{items.map(a=><article className="explore-card" key={a.slug}><img src={`https://images.unsplash.com/${a.image}?auto=format&fit=crop&w=800&q=80`} alt={`Illustrative ${a.name} activity`} loading="lazy"/><div><p className="eyebrow">{a.category} · {a.duration}</p><h2>{a.name}</h2><p>{a.description}</p><strong className="activity-price">{a.price?`${money(a.price)} / ${a.unit}`:'Included for overnight guests'}</strong><small className="sample-note">Sample offer</small><button className="text-link" onClick={()=>setSelected(selected===a.slug?'':a.slug)} aria-expanded={selected===a.slug}>{selected===a.slug?'Hide details':'View activity details'} ↗</button>{selected===a.slug&&<div className="activity-details"><p>{a.note}</p><p>This activity is a demonstration offer. Scheduling and reservations are not connected.</p></div>}</div></article>)}</div></>;}
export function ResortAmenities(){return <div className="resort-amenities">{['Beachfront setting','Swimming pool','All-day dining','Complimentary Wi-Fi','On-site parking','Room & activity options'].map(a=><span key={a}><Check size={17}/>{a}</span>)}</div>;}
